POST http://localhost:4000/users/register
Content-Type: application/json

{
    "email": "jan@gradic.net",
    "password": "jan"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "jan@gradic.net",
    "password": "jan"
}

###

GET http://localhost:4000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjliZDY2MTQyZGIyNTk2OTk0OTRmNjkiLCJ0d29mYSI6ZmFsc2UsImlhdCI6MTY1NDM4MDY1OCwiZXhwIjoxNjU2OTcyNjU4fQ.63vFCUtZSiLSSwb3-DpAXEflBTLkxPuuUjASqLIsa4M

###

PUT http://localhost:4000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjliZDY2MTQyZGIyNTk2OTk0OTRmNjkiLCJ0d29mYSI6ZmFsc2UsImlhdCI6MTY1NDM4MDY1OCwiZXhwIjoxNjU2OTcyNjU4fQ.63vFCUtZSiLSSwb3-DpAXEflBTLkxPuuUjASqLIsa4M
Content-Type: application/json

{
    "twofa": true
}